global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # FastAPI backend
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
